name: Like pizza

on:
  issue_comment:
    types:
      - created

jobs:
  create-branch:
    runs-on: ubuntu-latest
    # if: ${{ github.event.comment.body == 'Create Branch'}}
    permissions:
      issues: write
    steps:
      - name: Comment Start
        uses: actions/github-script@v6
        with:
          script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Creating branch now...'
              })
      - name: Create Issue Branch
        id: Create_Issue_Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
