name: Like pizza

on:
  issue_comment:
    types:
      - created

jobs:
  create-branch:
    runs-on: ubuntu-latest
    # if: ${{ github.event.comment.body == 'Create Branch'}}
    permissions:
      issues: write
    steps:
      - name: Create Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
