name: Create Branch For Issue

on:
  issue_comment:
    types:
      - created

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: peterjgrainger/action-create-branch@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes'
          sha: '${{ github.event.pull_request.head.sha }}'
        # uses: robvanderleek/create-issue-branch@main
        # env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
